name: Trigger Read the Docs Build

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  trigger_rtd:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Read the Docs Build
        env:
          RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
        run: |
          echo "Triggering RTD build for latest (main)"
          curl -X POST \
            -H "Authorization: Token $RTD_TOKEN" \
            -H "Content-Type: application/json" \
            "https://readthedocs.org/api/v3/projects/nfact/versions/latest/builds/"
