name: Trigger Read the Docs Build

on:
  pull_request:
    branches:
      - main  
    paths-ignore:
      - '**.md' 
      - '**/docs/**'

jobs:
  trigger_rtd:
    runs-on: ubuntu-latest
    steps:
      - name: Read the Docs Build
        env:
          RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Token $RTD_TOKEN" \
            "https://readthedocs.org/api/v3/projects/nfact/versions/latest/builds/"
